# Use the official devcontainer image as a base image
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-14

# Set build arguments for version defaults
ARG NODE_VERSION="18"
ARG PYTHON_VERSION="3.11"

# Install system packages and runtime dependencies
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    zsh \
    software-properties-common \
    libssl-dev \
    libffi-dev \
    python3-pip \
    python3-venv \
    && add-apt-repository ppa:deadsnakes/ppa -y \
    && apt-get update \
    && apt-get install -y python${PYTHON_VERSION} python${PYTHON_VERSION}-dev \
    && curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# Configure Python alternatives
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1 

# Switch to VS Code user
USER vscode

# Intall oh-my-zsh and plugins
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended \
    && git clone https://github.com/zsh-users/zsh-autosuggestions.git $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions \
    && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Configure user environment
ENV PATH="/home/vscode/.local/bin:/home/vscode/.local/bin:${PATH}" \
    SHELL=/bin/zsh \
    PYTHONPATH=/workspace

# Install Python tools
RUN Python3 -m pip install --user --upgrade pipx \
    && pipx install ensurepath \
    && pipx install poetry

# Set default shell and working directoty
WORKDIR /workspace
